name: mcm
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^0.5.8
  get: ^3.24.0
  fluttertoast: ^7.0.1
  flutter_spinkit: ^4.0.0
  intl: ^0.16.1
  google_fonts: ^1.1.2
  google_mobile_ads: ^0.11.0+4
  share_plus: ^1.2.0
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  pull_to_refresh: ^1.6.5
  in_app_update: ^1.1.15


  # do not update any of these
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.0.1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.1
  firebase_core: ^0.5.0
  provider: ^4.3.2
  # ...


dev_dependencies:
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
